<?xml version="1.0"?>
<!DOCTYPE mame [
<!ELEMENT mame (game+)>
    <!ATTLIST mame build CDATA #IMPLIED>
	<!ATTLIST mame debug (yes|no) "no">
	<!ATTLIST mame mameconfig CDATA #REQUIRED>
	<!ELEMENT game (description, year?, manufacturer?, biosset*, rom*, disk*, device_ref*, sample*, chip*, display*, sound?, input?, dipswitch*, configuration*, adjuster*, driver?, device*, slot*, softwarelist*, ramoption*)>
		<!ATTLIST game name CDATA #REQUIRED>
		<!ATTLIST game sourcefile CDATA #IMPLIED>
		<!ATTLIST game isbios (yes|no) "no">
		<!ATTLIST game isdevice (yes|no) "no">
		<!ATTLIST game ismechanical (yes|no) "no">
		<!ATTLIST game runnable (yes|no) "yes">
		<!ATTLIST game cloneof CDATA #IMPLIED>
		<!ATTLIST game romof CDATA #IMPLIED>
		<!ATTLIST game sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom optional (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk writable (yes|no) "no">
			<!ATTLIST disk status (baddump|nodump|good) "good">
			<!ATTLIST disk optional (yes|no) "no">
		<!ELEMENT device_ref EMPTY>
			<!ATTLIST device_ref name CDATA #REQUIRED>
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip tag CDATA #IMPLIED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT display EMPTY>
			<!ATTLIST display tag CDATA #IMPLIED>
			<!ATTLIST display type (raster|vector|lcd|unknown) #REQUIRED>
			<!ATTLIST display rotate (0|90|180|270) #REQUIRED>
			<!ATTLIST display flipx (yes|no) "no">
			<!ATTLIST display width CDATA #IMPLIED>
			<!ATTLIST display height CDATA #IMPLIED>
			<!ATTLIST display refresh CDATA #REQUIRED>
			<!ATTLIST display pixclock CDATA #IMPLIED>
			<!ATTLIST display htotal CDATA #IMPLIED>
			<!ATTLIST display hbend CDATA #IMPLIED>
			<!ATTLIST display hbstart CDATA #IMPLIED>
			<!ATTLIST display vtotal CDATA #IMPLIED>
			<!ATTLIST display vbend CDATA #IMPLIED>
			<!ATTLIST display vbstart CDATA #IMPLIED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT input (control*)>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input buttons CDATA #IMPLIED>
			<!ATTLIST input coins CDATA #IMPLIED>
			<!ELEMENT control EMPTY>
				<!ATTLIST control type CDATA #REQUIRED>
				<!ATTLIST control minimum CDATA #IMPLIED>
				<!ATTLIST control maximum CDATA #IMPLIED>
				<!ATTLIST control sensitivity CDATA #IMPLIED>
				<!ATTLIST control keydelta CDATA #IMPLIED>
				<!ATTLIST control reverse (yes|no) "no">
				<!ATTLIST control ways CDATA #IMPLIED>
				<!ATTLIST control ways2 CDATA #IMPLIED>
				<!ATTLIST control ways3 CDATA #IMPLIED>
		<!ELEMENT dipswitch (dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ATTLIST dipswitch tag CDATA #REQUIRED>
			<!ATTLIST dipswitch mask CDATA #REQUIRED>
			<!ELEMENT dipvalue EMPTY>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue value CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT configuration (confsetting*)>
			<!ATTLIST configuration name CDATA #REQUIRED>
			<!ATTLIST configuration tag CDATA #REQUIRED>
			<!ATTLIST configuration mask CDATA #REQUIRED>
			<!ELEMENT confsetting EMPTY>
				<!ATTLIST confsetting name CDATA #REQUIRED>
				<!ATTLIST confsetting value CDATA #REQUIRED>
				<!ATTLIST confsetting default (yes|no) "no">
		<!ELEMENT adjuster EMPTY>
			<!ATTLIST adjuster name CDATA #REQUIRED>
			<!ATTLIST adjuster default CDATA #REQUIRED>
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver color (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver sound (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver graphic (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver protection (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
			<!ATTLIST driver palettesize CDATA #REQUIRED>
		<!ELEMENT device (instance*, extension*)>
			<!ATTLIST device type CDATA #REQUIRED>
			<!ATTLIST device tag CDATA #IMPLIED>
			<!ATTLIST device mandatory CDATA #IMPLIED>
			<!ATTLIST device interface CDATA #IMPLIED>
			<!ELEMENT instance EMPTY>
				<!ATTLIST instance name CDATA #REQUIRED>
				<!ATTLIST instance briefname CDATA #REQUIRED>
			<!ELEMENT extension EMPTY>
				<!ATTLIST extension name CDATA #REQUIRED>
		<!ELEMENT slot (slotoption*)>
			<!ATTLIST slot name CDATA #REQUIRED>
			<!ELEMENT slotoption EMPTY>
				<!ATTLIST slotoption name CDATA #REQUIRED>
				<!ATTLIST slotoption devname CDATA #REQUIRED>
				<!ATTLIST slotoption default (yes|no) "no">
		<!ELEMENT softwarelist EMPTY>
			<!ATTLIST softwarelist name CDATA #REQUIRED>
			<!ATTLIST softwarelist status (original|compatible) #REQUIRED>
			<!ATTLIST softwarelist filter CDATA #IMPLIED>
		<!ELEMENT ramoption (#PCDATA)>
			<!ATTLIST ramoption default CDATA #IMPLIED>
]>
<mame build="0.148u2 (Mar 19 2013) - sample data" debug="no" mameconfig="10">
	<!--
	
	This is a sample data set for testing MAWS:
	- 005 - alphabetical first, no clones, imperfect empluation, samples, unused dips, baddump
	- 1941 - vertical on CPS1 hardware with 3 clones (1941j, 1941r1, 1941u)
	- 1942 - vertical on own hardware with 4 clones (1942a, 1942abl, 1942b, 1942w)
	- 39in1 - MAME emulation bootleg with 7 clones (19in1, 48in1, 48in1a, 48in1b, 4in1a, 4in1b, 60in1)
	- 3wonders - on CPS1 hardware with 4 clones (3wondersh, 3wondersr1, 3wondersu, wonder3)
	- kinst - on "Ultra64" hardware with CHD and 3 clones (kinst13, kinst14, kinstp)
	- kinst2 - on "Ultra64" hardware with CHD and 5 clones (kinst210, kinst211, kinst213, kinst2k3, kinst2k4)
	- dlair - laser disc nodump CHD and 6 clones (dlaira, dlairb, dlairc, dlaird, dlaire, dlairf) also nodump
	- darius - multiscreen and 3 clones (dariuse, dariusj, dariuso)
	- neogeo - BIOS with BIOS sets, games include viewpoin and pbobblen (with bootleg clone pbobblenb)
	- outrun - different cabinets, mulitple controls, and bootleg, four clones (outrunb, outrundx, outruno, outrunra)
	- firemntn - imprefect emulation elecromechanical unique, samples from genpin, no screen
	
	Cases:
	- Hardware: electromechanical, multi-screen, vertical screen, multi-controls, 
	- ROM/relationship: BIOS, BIOS SET, nodump/baddump, clones, unique, samples, "systems" (CPS, NeoGeo), CHD, Laserdisk
	- Service: unknown/unused dip switches
	? Other: Multi-CHD, working electromechanical, device, software list, slot, configuration
	
	-->
	<!-- segag80r.c -->
	<game name="005" sourcefile="segag80r.c" sampleof="005">
		<description>005</description>
		<year>1981</year>
		<manufacturer>Sega</manufacturer>
		<rom name="1346b.cpu-u25" size="2048" crc="8e68533e" sha1="a257c556d31691068ed5c991f1fb2b51da4826db" region="maincpu" offset="0"/>
		<rom name="5092.prom-u1" size="2048" crc="29e10a81" sha1="c4b4e6c75bcf276e53f39a456d8d633c83dcf485" region="maincpu" offset="800"/>
		<rom name="5093.prom-u2" size="2048" crc="e1edc3df" sha1="4f593546bbb0f50850dc6286cb514af6831c27a7" region="maincpu" offset="1000"/>
		<rom name="5094.prom-u3" size="2048" crc="995773bb" sha1="98dd826527853bc031edfb9a821778cc3e906150" region="maincpu" offset="1800"/>
		<rom name="5095.prom-u4" size="2048" crc="f887f575" sha1="de96573a91b60b090b1f441f1410ecad63c9467c" region="maincpu" offset="2000"/>
		<rom name="5096.prom-u5" size="2048" crc="5545241e" sha1="ee504ccaab469100137717341a1b461175ff792d" region="maincpu" offset="2800"/>
		<rom name="5097.prom-u6" size="2048" crc="428edb54" sha1="4f3df6017068d939014a8f638f28e3228acb7add" region="maincpu" offset="3000"/>
		<rom name="5098.prom-u7" size="2048" crc="5bcb9d63" sha1="c0c91bc9f75ad88a6e15c554a980d5c075725fe8" region="maincpu" offset="3800"/>
		<rom name="5099.prom-u8" size="2048" crc="0ea24ba3" sha1="95a30c9b63ef1c346df0da71af3fdecd1a75cb8f" region="maincpu" offset="4000"/>
		<rom name="5100.prom-u9" size="2048" crc="a79af131" sha1="0ba34130174e196015bc9b9c135c420209dfd524" region="maincpu" offset="4800"/>
		<rom name="5101.prom-u10" size="2048" crc="8a1cdae0" sha1="f7c617f9bdb7818e6069a981d0c8820deade134c" region="maincpu" offset="5000"/>
		<rom name="5102.prom-u11" size="2048" crc="70826a15" sha1="a86322d0e8a88534e9b78dcde42ae4c441276913" region="maincpu" offset="5800"/>
		<rom name="5103.prom-u12" size="2048" crc="7f80c5b0" sha1="00748cd5fc7f75fdca194e748524d406c006296d" region="maincpu" offset="6000"/>
		<rom name="5104.prom-u13" size="2048" crc="0140930e" sha1="f8ef894c46d3663bd89d2d817675a67075d3e0d6" region="maincpu" offset="6800"/>
		<rom name="5105.prom-u14" size="2048" crc="17807a05" sha1="bd99f5beab0155f6e4d2fab2fa5f4e147c5730d5" region="maincpu" offset="7000"/>
		<rom name="5106.prom-u15" size="2048" crc="c7cdfa9d" sha1="6ab7adc60ac7bb53a7175e8de51924008737c9ac" region="maincpu" offset="7800"/>
		<rom name="5107.prom-u16" size="2048" crc="95f8a2e6" sha1="89c92e000b3e1630380db779370cf9f5b13e5719" region="maincpu" offset="8000"/>
		<rom name="5108.prom-u17" size="2048" crc="d371cacd" sha1="8f2cdcc0b4e3b77e0958d257e37accefc5749cde" region="maincpu" offset="8800"/>
		<rom name="5109.prom-u18" size="2048" crc="48a20617" sha1="5b4bc3beda0404ff0a61bb42751b87f71817f363" region="maincpu" offset="9000"/>
		<rom name="5110.prom-u19" size="2048" crc="7d26111a" sha1="a6d3652ae606a5b75026e524c9d6aaa78300741e" region="maincpu" offset="9800"/>
		<rom name="5111.prom-u20" size="2048" crc="a888e175" sha1="4c0af94441bf51dfc852372a5b90d0830df81363" region="maincpu" offset="a000"/>
		<rom name="epr-1286.sound-16" size="2048" crc="fbe0d501" sha1="bfa277689790f835d8a43be4beee0581e1096bcc" region="005" offset="0"/>
		<rom name="6331.sound-u8" size="32" crc="1d298cb0" sha1="bb0bb62365402543e3154b9a77be9c75010e6abc" status="baddump" region="proms" offset="0"/>
		<sample name="lexplode"/>
		<sample name="sexplode"/>
		<sample name="dropbomb"/>
		<sample name="shoot"/>
		<sample name="missile"/>
		<sample name="helicopt"/>
		<sample name="whistle"/>
		<chip type="cpu" tag="maincpu" name="Z80" clock="3867000"/>
		<chip type="audio" tag="mono" name="Speaker"/>
		<chip type="audio" tag="samples" name="Samples"/>
		<chip type="audio" tag="005" name="005 Custom"/>
		<display tag="screen" type="raster" rotate="270" width="256" height="224" refresh="59.998138" pixclock="5156000" htotal="328" hbend="0" hbstart="256" vtotal="262" vbend="0" vbstart="224" />
		<sound channels="1"/>
		<input players="2" buttons="1" coins="2" service="yes">
			<control type="joy" ways="4"/>
		</input>
		<dipswitch name="Lives" tag="Lives" mask="3">
			<dipvalue name="3" value="0" default="yes"/>
			<dipvalue name="4" value="2"/>
			<dipvalue name="5" value="1"/>
			<dipvalue name="6" value="3"/>
		</dipswitch>
		<dipswitch name="Cabinet" tag="Cabinet" mask="4">
			<dipvalue name="Upright" value="4" default="yes"/>
			<dipvalue name="Cocktail" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="Unused" mask="8">
			<dipvalue name="Off" value="8" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="Unused" mask="16">
			<dipvalue name="Off" value="16" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="Unused" mask="32">
			<dipvalue name="Off" value="32" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="Unused" mask="64">
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="Unused" mask="128">
			<dipvalue name="Off" value="128" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Coin A" tag="Coin A" mask="15">
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="1"/>
			<dipvalue name="2 Coins/1 Credit" value="2"/>
			<dipvalue name="2 Coins/1 Credit 5/3 6/4" value="9"/>
			<dipvalue name="2 Coins/1 Credit 4/3" value="10"/>
			<dipvalue name="1 Coin/1 Credit" value="3" default="yes"/>
			<dipvalue name="1 Coin/1 Credit 5/6" value="11"/>
			<dipvalue name="1 Coin/1 Credit 4/5" value="12"/>
			<dipvalue name="1 Coin/1 Credit 2/3" value="13"/>
			<dipvalue name="1 Coin/2 Credits" value="4"/>
			<dipvalue name="1 Coin/2 Credits 5/11" value="14"/>
			<dipvalue name="1 Coin/2 Credits 4/9" value="15"/>
			<dipvalue name="1 Coin/3 Credits" value="5"/>
			<dipvalue name="1 Coin/4 Credits" value="6"/>
			<dipvalue name="1 Coin/5 Credits" value="7"/>
			<dipvalue name="1 Coin/6 Credits" value="8"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="Coin B" mask="240">
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="16"/>
			<dipvalue name="2 Coins/1 Credit" value="32"/>
			<dipvalue name="2 Coins/1 Credit 5/3 6/4" value="144"/>
			<dipvalue name="2 Coins/1 Credit 4/3" value="160"/>
			<dipvalue name="1 Coin/1 Credit" value="48" default="yes"/>
			<dipvalue name="1 Coin/1 Credit 5/6" value="176"/>
			<dipvalue name="1 Coin/1 Credit 4/5" value="192"/>
			<dipvalue name="1 Coin/1 Credit 2/3" value="208"/>
			<dipvalue name="1 Coin/2 Credits" value="64"/>
			<dipvalue name="1 Coin/2 Credits 5/11" value="224"/>
			<dipvalue name="1 Coin/2 Credits 4/9" value="240"/>
			<dipvalue name="1 Coin/3 Credits" value="80"/>
			<dipvalue name="1 Coin/4 Credits" value="96"/>
			<dipvalue name="1 Coin/5 Credits" value="112"/>
			<dipvalue name="1 Coin/6 Credits" value="128"/>
		</dipswitch>
		<driver status="imperfect" emulation="good" color="good" sound="imperfect" graphic="good" savestate="unsupported" palettesize="64"/>
	</game>
	<!-- cps1.c -->
	<game name="1941" sourcefile="cps1.c">
		<description>1941: Counter Attack (World 900227)</description>
		<year>1990</year>
		<manufacturer>Capcom</manufacturer>
		<rom name="41em_30.11f" size="131072" crc="4249ec61" sha1="5323cfa6938e6d95db8469f09b2fb5b5c5068bfc" region="maincpu" offset="0"/>
		<rom name="41em_35.11h" size="131072" crc="ddbee5eb" sha1="0fef53398f4e2cd6ccc7bc122dd893e0a4e2e052" region="maincpu" offset="1"/>
		<rom name="41em_31.12f" size="131072" crc="584e88e5" sha1="af254408d939cc439b5653e60afbccdf59777085" region="maincpu" offset="40000"/>
		<rom name="41em_36.12h" size="131072" crc="3cfc31d0" sha1="7c0614e4e25502ff2d18aa4a97c91bf05ead875f" region="maincpu" offset="40001"/>
		<rom name="41-32m.8h" size="524288" crc="4e9648ca" sha1="d8e67e6e3a6dc79053e4f56cfd83431385ea7611" region="maincpu" offset="80000"/>
		<rom name="41-5m.7a" size="524288" crc="01d1cb11" sha1="621e5377d1aaa9f7270d85bea1bdeef6721cdd05" region="gfx" offset="0"/>
		<rom name="41-7m.9a" size="524288" crc="aeaa3509" sha1="6124ef06d9dfdd879181856bd49853f1800c3b87" region="gfx" offset="2"/>
		<rom name="41-1m.3a" size="524288" crc="ff77985a" sha1="7e08df3a829bf9617470a46c79b713d4d9ebacae" region="gfx" offset="4"/>
		<rom name="41-3m.5a" size="524288" crc="983be58f" sha1="83a4decdd775f859240771269b8af3a5981b244c" region="gfx" offset="6"/>
		<rom name="41_9.12b" size="65536" crc="0f9d8527" sha1="3a00dd5772f38081fde11d8d61ba467379e2a636" region="audiocpu" offset="0"/>
		<rom name="41_18.11c" size="131072" crc="d1f15aeb" sha1="88089383f2d54fc97026a67f067d448eee5bd0c2" region="oki" offset="0"/>
		<rom name="41_19.12c" size="131072" crc="15aec3a6" sha1="8153c03aba005bab62bf0e8b3d15ec1c346326fd" region="oki" offset="20000"/>
		<rom name="buf1" size="279" crc="eb122de7" sha1="b26b5bfe258e3e184f069719f9fd008d6b8f6b9b" region="aboardplds" offset="0"/>
		<rom name="ioa1" size="279" crc="59c7ee3b" sha1="fbb887c5b4f5cb8df77cec710eaac2985bc482a6" region="aboardplds" offset="0"/>
		<rom name="prg1" size="279" crc="f1129744" sha1="a5300f301c1a08a7da768f0773fa0fe3f683b237" region="aboardplds" offset="0"/>
		<rom name="rom1" size="279" crc="41dc73b9" sha1="7d4c9f1693c821fbf84e32dd6ef62ddf14967845" region="aboardplds" offset="0"/>
		<rom name="sou1" size="279" crc="84f4b2fe" sha1="dcc9e86cc36316fe42eace02d6df75d08bc8bb6d" region="aboardplds" offset="0"/>
		<rom name="yi24b.1a" size="279" crc="3004dcdf" sha1="a73d86d1545af1d99a03d88af83449ec82b03c5c" region="bboardplds" offset="0"/>
		<rom name="iob1.11e" size="279" crc="3abc0700" sha1="973043aa46ec6d5d1db20dc9d5937005a0f9f6ae" region="bboardplds" offset="0"/>
		<chip type="cpu" tag="maincpu" name="68000" clock="10000000"/>
		<chip type="cpu" tag="audiocpu" name="Z80" clock="3579545"/>
		<chip type="audio" tag="mono" name="Speaker"/>
		<chip type="audio" tag="2151" name="YM2151" clock="3579545"/>
		<chip type="audio" tag="oki" name="OKI6295" clock="1000000"/>
		<display tag="screen" type="raster" rotate="270" width="384" height="224" refresh="59.629403" pixclock="8000000" htotal="518" hbend="64" hbstart="448" vtotal="259" vbend="16" vbstart="240" />
		<sound channels="1"/>
		<input players="2" buttons="2" coins="2">
			<control type="joy" ways="8"/>
		</input>
		<dipswitch name="Service Mode" tag="Service Mode" mask="64">
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Coin A" tag="Coin A" mask="7">
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="1"/>
			<dipvalue name="2 Coins/1 Credit" value="2"/>
			<dipvalue name="1 Coin/1 Credit" value="7" default="yes"/>
			<dipvalue name="1 Coin/2 Credits" value="6"/>
			<dipvalue name="1 Coin/3 Credits" value="5"/>
			<dipvalue name="1 Coin/4 Credits" value="4"/>
			<dipvalue name="1 Coin/6 Credits" value="3"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="Coin B" mask="56">
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="8"/>
			<dipvalue name="2 Coins/1 Credit" value="16"/>
			<dipvalue name="1 Coin/1 Credit" value="56" default="yes"/>
			<dipvalue name="1 Coin/2 Credits" value="48"/>
			<dipvalue name="1 Coin/3 Credits" value="40"/>
			<dipvalue name="1 Coin/4 Credits" value="32"/>
			<dipvalue name="1 Coin/6 Credits" value="24"/>
		</dipswitch>
		<dipswitch name="2 Coins to Start, 1 to Continue" tag="2 Coins to Start, 1 to Continue" mask="64">
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="Unused" mask="128">
			<dipvalue name="Off" value="128" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Difficulty" tag="Difficulty" mask="7">
			<dipvalue name="1 (Easiest)" value="7"/>
			<dipvalue name="2" value="6"/>
			<dipvalue name="3" value="5"/>
			<dipvalue name="4 (Normal)" value="4" default="yes"/>
			<dipvalue name="5" value="3"/>
			<dipvalue name="6" value="2"/>
			<dipvalue name="7" value="1"/>
			<dipvalue name="8 (Hardest)" value="0"/>
		</dipswitch>
		<dipswitch name="Level Up Timer" tag="Level Up Timer" mask="24">
			<dipvalue name="More Slowly" value="24" default="yes"/>
			<dipvalue name="Slowly" value="16"/>
			<dipvalue name="Quickly" value="8"/>
			<dipvalue name="More Quickly" value="0"/>
		</dipswitch>
		<dipswitch name="Bullet's Speed" tag="Bullet's Speed" mask="96">
			<dipvalue name="Very Slow" value="96" default="yes"/>
			<dipvalue name="Slow" value="64"/>
			<dipvalue name="Fast" value="32"/>
			<dipvalue name="Very Fast" value="0"/>
		</dipswitch>
		<dipswitch name="Initial Vitality" tag="Initial Vitality" mask="128">
			<dipvalue name="3 Bars" value="128" default="yes"/>
			<dipvalue name="4 Bars" value="0"/>
		</dipswitch>
		<dipswitch name="Throttle Game Speed" tag="Throttle Game Speed" mask="1">
			<dipvalue name="Off" value="0"/>
			<dipvalue name="On" value="1" default="yes"/>
		</dipswitch>
		<dipswitch name="Unused" tag="Unused" mask="2">
			<dipvalue name="Off" value="2" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Free Play" tag="Free Play" mask="4">
			<dipvalue name="Off" value="4" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Freeze" tag="Freeze" mask="8">
			<dipvalue name="Off" value="8" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Flip Screen" tag="Flip Screen" mask="16">
			<dipvalue name="Off" value="16" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Demo Sounds" tag="Demo Sounds" mask="32">
			<dipvalue name="Off" value="32"/>
			<dipvalue name="On" value="0" default="yes"/>
		</dipswitch>
		<dipswitch name="Allow Continue" tag="Allow Continue" mask="64">
			<dipvalue name="No" value="64"/>
			<dipvalue name="Yes" value="0" default="yes"/>
		</dipswitch>
		<dipswitch name="Game Mode" tag="Game Mode" mask="128">
			<dipvalue name="Game" value="128" default="yes"/>
			<dipvalue name="Test" value="0"/>
		</dipswitch>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported" palettesize="3072"/>
	</game>
	<game name="1941j" sourcefile="cps1.c" cloneof="1941" romof="1941">
		<description>1941: Counter Attack (Japan)</description>
		<year>1990</year>
		<manufacturer>Capcom</manufacturer>
		<rom name="41_36.12f" size="131072" crc="7fbd42ab" sha1="4e52a599e3099bf3cccabb89152c69f216fde79e" region="maincpu" offset="0"/>
		<rom name="41_42.12h" size="131072" crc="c7781f89" sha1="7e99c433de0c903791ae153a3cc8632042b0a90d" region="maincpu" offset="1"/>
		<rom name="41_37.13f" size="131072" crc="c6464b0b" sha1="abef422d891d32334a858d49599f1ef7cf0db45d" region="maincpu" offset="40000"/>
		<rom name="41_43.13h" size="131072" crc="440fc0b5" sha1="e725535533c25a2c80a45a2200bbfd0dcda5ed97" region="maincpu" offset="40001"/>
		<rom name="41_34.10f" size="131072" crc="b5f341ec" sha1="95c740332e9e05250979a098e951600ca89cfde4" region="maincpu" offset="80000"/>
		<rom name="41_40.10h" size="131072" crc="3979837d" sha1="e35bca5cd6f7559447c553c7866a3934080ca018" region="maincpu" offset="80001"/>
		<rom name="41_35.11f" size="131072" crc="95cc979a" sha1="96a22d2accdcd1ed3829ab0e1f17c1615f8bb2a9" region="maincpu" offset="c0000"/>
		<rom name="41_41.11h" size="131072" crc="57496819" sha1="fe705a25a2c6523c3bc0105f4b183931c5ffcc81" region="maincpu" offset="c0001"/>
		<rom name="41_09.4b" size="131072" crc="be1b6bc2" sha1="0b11efb7adf6bb9c5fdef702171edd38c149e338" region="gfx" offset="0"/>
		<rom name="41_01.4a" size="131072" crc="d8946fc1" sha1="e18d2bd5517a9a74973f5a505e59e400db3843e2" region="gfx" offset="1"/>
		<rom name="41_13.9b" size="131072" crc="2e06d0ec" sha1="b7c886dce6bc5eefa34e39faec658dd9df34f82c" region="gfx" offset="2"/>
		<rom name="41_05.9a" size="131072" crc="d8ba28e0" sha1="dd1908166b32cf3bb3222f6d3febc21371463395" region="gfx" offset="3"/>
		<rom name="41_24.5e" size="131072" crc="5aa43cee" sha1="15e1aa2fee8deb25eefba067395961fee3e4c84d" region="gfx" offset="4"/>
		<rom name="41_17.5c" size="131072" crc="bbeff902" sha1="1bf421072387ab7d59b57ecd33cb5ae6fd8ecd06" region="gfx" offset="5"/>
		<rom name="41_38.8h" size="131072" crc="8889c0aa" sha1="23b74cc78fe1057c1776ea1f7371801441125a85" region="gfx" offset="6"/>
		<rom name="41_32.8f" size="131072" crc="f0168249" sha1="1ce2330ea4460e7e72f16a1f7edbfa8abba6b5a0" region="gfx" offset="7"/>
		<rom name="41_10.5b" size="131072" crc="b7eb6a6d" sha1="444b49e81cd46e90a9e1dfcf465f19c38189b2d7" region="gfx" offset="100000"/>
		<rom name="41_02.5a" size="131072" crc="802e8153" sha1="baf19220c53949dac0d0b75368d5f1ee6c32b619" region="gfx" offset="100001"/>
		<rom name="41_14.10b" size="131072" crc="5a33f676" sha1="96794463ddfae7ce4a7d7e6b65ff1b8da7b3dd74" region="gfx" offset="100002"/>
		<rom name="41_06.10a" size="131072" crc="4e53650b" sha1="a5b19b1ce38f04296dee38d35015869607ecc260" region="gfx" offset="100003"/>
		<rom name="41_25.7e" size="131072" crc="94add360" sha1="6f3542f028bdc453d0254de599b124240ea98259" region="gfx" offset="100004"/>
		<rom name="41_18.7c" size="131072" crc="a5e1c1f3" sha1="1961ad3c8965c51da8a19a7283333f3a19bb2030" region="gfx" offset="100005"/>
		<rom name="41_39.9h" size="131072" crc="5b5c3949" sha1="485b1baecee6bb9a6667baf404375fc758bdfb76" region="gfx" offset="100006"/>
		<rom name="41_33.9f" size="131072" crc="7a31b0e2" sha1="f2eca12f4e89266d923a94d0837c555bc1c6cb29" region="gfx" offset="100007"/>
		<rom name="41_23.13b" merge="41_9.12b" size="65536" crc="0f9d8527" sha1="3a00dd5772f38081fde11d8d61ba467379e2a636" region="audiocpu" offset="0"/>
		<rom name="41_30.12c" merge="41_18.11c" size="131072" crc="d1f15aeb" sha1="88089383f2d54fc97026a67f067d448eee5bd0c2" region="oki" offset="0"/>
		<rom name="41_31.13c" merge="41_19.12c" size="131072" crc="15aec3a6" sha1="8153c03aba005bab62bf0e8b3d15ec1c346326fd" region="oki" offset="20000"/>
		<rom name="buf1" merge="buf1" size="279" crc="eb122de7" sha1="b26b5bfe258e3e184f069719f9fd008d6b8f6b9b" region="aboardplds" offset="0"/>
		<rom name="ioa1" merge="ioa1" size="279" crc="59c7ee3b" sha1="fbb887c5b4f5cb8df77cec710eaac2985bc482a6" region="aboardplds" offset="0"/>
		<rom name="prg1" merge="prg1" size="279" crc="f1129744" sha1="a5300f301c1a08a7da768f0773fa0fe3f683b237" region="aboardplds" offset="0"/>
		<rom name="rom1" merge="rom1" size="279" crc="41dc73b9" sha1="7d4c9f1693c821fbf84e32dd6ef62ddf14967845" region="aboardplds" offset="0"/>
		<rom name="sou1" merge="sou1" size="279" crc="84f4b2fe" sha1="dcc9e86cc36316fe42eace02d6df75d08bc8bb6d" region="aboardplds" offset="0"/>
		<rom name="yi22b.1a" size="279" status="nodump" region="bboardplds" offset="0"/>
		<rom name="lwio.12e" size="279" crc="ad52b90c" sha1="f0fd6aeea515ee449320fe15684e6b3ab7f97bf4" region="bboardplds" offset="0"/>
		<chip type="cpu" tag="maincpu" name="68000" clock="10000000"/>
		<chip type="cpu" tag="audiocpu" name="Z80" clock="3579545"/>
		<chip type="audio" tag="mono" name="Speaker"/>
		<chip type="audio" tag="2151" name="YM2151" clock="3579545"/>
		<chip type="audio" tag="oki" name="OKI6295" clock="1000000"/>
		<display tag="screen" type="raster" rotate="270" width="384" height="224" refresh="59.629403" pixclock="8000000" htotal="518" hbend="64" hbstart="448" vtotal="259" vbend="16" vbstart="240" />
		<sound channels="1"/>
		<input players="2" buttons="2" coins="2">
			<control type="joy" ways="8"/>
		</input>
		<dipswitch name="Service Mode" tag="Service Mode" mask="64">
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Coin A" tag="Coin A" mask="7">
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="1"/>
			<dipvalue name="2 Coins/1 Credit" value="2"/>
			<dipvalue name="1 Coin/1 Credit" value="7" default="yes"/>
			<dipvalue name="1 Coin/2 Credits" value="6"/>
			<dipvalue name="1 Coin/3 Credits" value="5"/>
			<dipvalue name="1 Coin/4 Credits" value="4"/>
			<dipvalue name="1 Coin/6 Credits" value="3"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="Coin B" mask="56">
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="8"/>
			<dipvalue name="2 Coins/1 Credit" value="16"/>
			<dipvalue name="1 Coin/1 Credit" value="56" default="yes"/>
			<dipvalue name="1 Coin/2 Credits" value="48"/>
			<dipvalue name="1 Coin/3 Credits" value="40"/>
			<dipvalue name="1 Coin/4 Credits" value="32"/>
			<dipvalue name="1 Coin/6 Credits" value="24"/>
		</dipswitch>
		<dipswitch name="2 Coins to Start, 1 to Continue" tag="2 Coins to Start, 1 to Continue" mask="64">
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="Unused" mask="128">
			<dipvalue name="Off" value="128" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Difficulty" tag="Difficulty" mask="7">
			<dipvalue name="1 (Easiest)" value="7"/>
			<dipvalue name="2" value="6"/>
			<dipvalue name="3" value="5"/>
			<dipvalue name="4 (Normal)" value="4" default="yes"/>
			<dipvalue name="5" value="3"/>
			<dipvalue name="6" value="2"/>
			<dipvalue name="7" value="1"/>
			<dipvalue name="8 (Hardest)" value="0"/>
		</dipswitch>
		<dipswitch name="Level Up Timer" tag="Level Up Timer" mask="24">
			<dipvalue name="More Slowly" value="24" default="yes"/>
			<dipvalue name="Slowly" value="16"/>
			<dipvalue name="Quickly" value="8"/>
			<dipvalue name="More Quickly" value="0"/>
		</dipswitch>
		<dipswitch name="Bullet's Speed" tag="Bullet's Speed" mask="96">
			<dipvalue name="Very Slow" value="96" default="yes"/>
			<dipvalue name="Slow" value="64"/>
			<dipvalue name="Fast" value="32"/>